AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'spec_money/**/*'
    - 'spec_money_rails/**/*'
    - 'vendor/**/*'

Style/AccessorGrouping:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
